[package]
name = "hw-ffi"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ble-transport = { path = "../ble-transport", features = ["trezor-safe7"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
trezor-connect = { path = "../trezor-connect", features = ["ble"] }
uniffi = { version = "0.30", features = ["tokio"] }
uniffi_macros = "0.30"
uuid = "1"
